language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=2.1.4

before_script:
  - curl -s http://getcomposer.org/installer | php --
  - php composer.phar install --dev
  - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - helios.ag@gmail.com
